### ISSUE TITLE
Switching scenes without confirmation

### ISSUE THREAD

**Issue by scy** [malliaridis/obssd#28]
# Feature Request

### Describe your idea

Currently, to switch to scene, I have to select it and then hit the small button on the bottom of the screen to actually activate it. I’d prefer to switch between scenes with a single tap.

Not sure whether this is already available. I’ve tried long-pressing a scene and double-tapping it, didn’t help. I also couldn’t find an option for this in the app’s settings or on the scenes screen.

### Expected behavior and realization

Add a boolean option to the settings called something like “instant scene switching” or something like this. If active, the scene switching button on the bottom of the screen goes away and tapping a scene causes it to instantly become active. (Of course the scene transition effect still plays, it’s just a UI change.)

Thanks for the app by the way!

**Comment by malliaridis** [comment]
I had that in mind when I designed the screen for the scene transitions. I decided back then that a second click will prevent accidental scene transitions through miss-clicks.

But adding an option to turn that "safety" click on or off is probably a better approach and having single click as default configuration I think results to better usability. I will plan a minor update then and add that functionality together with some other minor fixes.

**Comment by malliaridis** [comment]
I have successfully implemented this feature providing three options of scene switching: single tap (directly switching, default), double tap (first click selection, second click switch) and the current floating button (selection only until floating button is clicked).

The next update including the changes is coming next week. :)
