### ISSUE TITLE
How to find the computer address

### ISSUE THREAD

**Issue by MASSANGA** [malliaridis/obssd#41]

**Comment by malliaridis** [comment]
Hey @MASSANGA, sorry for the late response.

Ona Windows PC you can press the Windows Key + R, type in `cmd.exe` and in the new window (the command prompt) type `ipconfig`. There you get a list of available network adapters of your PC. The one you are looking for is probably called something like "Ethernet adapter Ethernet". There, you can find the entry called "IPv4 Address", which is the IP address of your PC for that specific adapter.

The port should be 4444 if you haven't changed it in the plugin.
![ipconfig](https://user-images.githubusercontent.com/33470669/161049137-e7dd2887-4a19-43c8-aad0-40188cf84292.png)

After getting these two information, you can insert in the current version of the app (v1.x) in the input field the address and the port seperated by a semicolon. For example: `192.168.178.23:4444`.

In case you need further assistance or succeeded feel free to report back. For now, I will close this issue. :)
