### ISSUE TITLE
Move to WebSocket v0.5

### ISSUE THREAD

**Issue by barkermn01** [malliaridis/obssd#46]
Could the app be updated to support the new OBS that has moved the Web socket system in to the main app and changed the API spec.

**Comment by malliaridis** [comment]
Thanks for opening that issue. I plan to start working on the project again on mid of November (I lack on time right now). The next update will introduce a few optimizations, including a QR code scanner for a quicker and less error prone connection establishment and support for Streamlabs OBS.

I will leave this ticket open until the major update has been released.
