### ISSUE TITLE
wo ist die ip vom pc

### ISSUE THREAD

**Issue by Patrickwze2008** [malliaridis/obssd#51]

**Comment by Patrickwze2008** [comment]
wo ist die ip vom pc

**Comment by malliaridis** [comment]
Die IP Adresse des PCs kann in den Netzwerkeinstellungen gefunden werden oder über einen CMD/Terminal Befehl. Da ich nicht genau weiß, welches System du verwendest, empfehle ich dir zu googlen oder ChatGPT zz fragen. Es gibt hierzu zahlreiche Anleitungen und Informationen online welche es Schritt für Schritt erklären.

Für Windows kann z.B. Microsoft's Seite hilfreich sein:

https://support.microsoft.com/de-de/windows/suchen-sie-ihre-ip-adresse-in-windows-f21a9bbc-c582-55cd-35e0-73431160a1b9
